const data = {
  retrato: {
    title: "Retrato",
    desc: "Fotografía de retrato profesional",
    image: "assets/images/retrato/retrato1.jpeg",
    carrusel : [
      "assets/images/retrato/retrato_1.jpg",
      "assets/images/retrato/retrato_5.jpg",
      "assets/images/retrato/retrato_6.jpg",
    ],
    photos: [
      "assets/images/retrato/retrato_1.jpg",
      "assets/images/retrato/retrato_2.jpg",
      "assets/images/retrato/retrato_3.jpg",
      "assets/images/retrato/retrato_4.jpg",
      "assets/images/retrato/retrato_5.jpg",
      "assets/images/retrato/retrato_6.jpg",
    ],
  },
  paisaje: {
    title: "Paisaje",
    desc: "Fotografía de paisajes impresionantes",
    image: "assets/images/paisaje/paisaje_1.jpg",
    carrusel : [
      "assets/images/paisaje/paisaje_1.jpg",
      "assets/images/paisaje/paisaje_2.jpg",
      "assets/images/paisaje/paisaje_3.jpg",
    ],
    photos: [
      "assets/images/paisaje/paisaje_1.jpg",
      "assets/images/paisaje/paisaje_2.jpg",
      "assets/images/paisaje/paisaje_3.jpg",
      "assets/images/paisaje/paisaje_4.jpg",
      "assets/images/paisaje/paisaje_5.jpg",
      "assets/images/paisaje/paisaje_6.jpg",
      "assets/images/paisaje/paisaje_7.jpg",
      "assets/images/paisaje/paisaje_8.jpg",
      "assets/images/paisaje/paisaje_9.jpg",
      "assets/images/paisaje/paisaje_10.jpg",
      "assets/images/paisaje/paisaje_11.jpg",
      "assets/images/paisaje/paisaje_12.jpg",
    ],
  },
  fauna: {
    title: "Fauna",
    desc: "Fotografía de animales en su hábitat natural",
    image: "assets/images/fauna/fauna_6.jpg",
    carrusel : [
      "assets/images/fauna/fauna_1.jpg",
      "assets/images/fauna/fauna_4.jpg",
      "assets/images/fauna/fauna_6.jpg",
    ],
    photos: [
      "assets/images/fauna/fauna_1.jpg",
      "assets/images/fauna/fauna_2.jpg",
      "assets/images/fauna/fauna_3.jpg",
      "assets/images/fauna/fauna_4.jpg",
      "assets/images/fauna/fauna_5.jpg",
      "assets/images/fauna/fauna_6.jpg",
      "assets/images/fauna/fauna_7.jpg",
      "assets/images/fauna/fauna_8.jpg",
      "assets/images/fauna/fauna_9.jpg",
    ],
  },
  astrofotografia: {
    title: "Astrofotografía",
    desc: "Fotografía del cielo y el universo",
    image: "assets/images/astro/astro_1.jpg",
    carrusel : [
      "assets/images/astro/astro_1.jpg",
      "assets/images/astro/astro_4.jpg",
    ],
    photos: [
      "assets/images/astro/astro_1.jpg",
      "assets/images/astro/astro_2.jpg",
      "assets/images/astro/astro_3.jpg",
      "assets/images/astro/astro_4.jpg",
      "assets/images/astro/astro_5.jpg",
      "assets/images/astro/astro_6.jpg",
      "assets/images/astro/astro_7.jpg",
    ],
  },
  deporte: {
    title: "Deporte",
    desc: "Capturas de deportes y acción",
    image: "assets/images/deporte/deporte1.jpeg",
    carrusel : [],
    photos: [
      "assets/images/deporte/deporte1.jpeg",
      "assets/images/deporte/deporte2.jpeg",
    ],
  },
};