const data = {
  retrato: {
    title: "Retrato",
    desc: "Fotografía de retrato profesional",
    image: "assets/images/retrato/retrato1.jpeg",
    carrusel : [
      "assets/images/retrato/retrato_1.webp",
      "assets/images/retrato/retrato_5.webp",
      "assets/images/retrato/retrato_6.webp",
    ],
    photos: [
      "assets/images/retrato/retrato_1.webp",
      "assets/images/retrato/retrato_2.webp",
      "assets/images/retrato/retrato_3.webp",
      "assets/images/retrato/retrato_4.webp",
      "assets/images/retrato/retrato_5.webp",
      "assets/images/retrato/retrato_6.webp",
    ],
  },
  paisaje: {
    title: "Paisaje",
    desc: "Fotografía de paisajes impresionantes",
    image: "assets/images/paisaje/paisaje_1.webp",
    carrusel : [
      "assets/images/paisaje/paisaje_1.webp",
      "assets/images/paisaje/paisaje_2.webp",
      "assets/images/paisaje/paisaje_3.webp",
    ],
    photos: [
      "assets/images/paisaje/paisaje_1.webp",
      "assets/images/paisaje/paisaje_2.webp",
      "assets/images/paisaje/paisaje_3.webp",
      "assets/images/paisaje/paisaje_4.webp",
      "assets/images/paisaje/paisaje_5.webp",
      "assets/images/paisaje/paisaje_6.webp",
      "assets/images/paisaje/paisaje_7.webp",
      "assets/images/paisaje/paisaje_8.webp",
      "assets/images/paisaje/paisaje_9.webp",
      "assets/images/paisaje/paisaje_10.webp",
      "assets/images/paisaje/paisaje_11.webp",
      "assets/images/paisaje/paisaje_12.webp",
      "assets/images/paisaje/paisaje_13.webp",
    ],
  },
  fauna: {
    title: "Fauna",
    desc: "Fotografía de animales en su hábitat natural",
    image: "assets/images/fauna/fauna_6.webp",
    carrusel : [
      "assets/images/fauna/fauna_1.webp",
      "assets/images/fauna/fauna_4.webp",
      "assets/images/fauna/fauna_6.webp",
    ],
    photos: [
      "assets/images/fauna/fauna_1.webp",
      "assets/images/fauna/fauna_2.webp",
      "assets/images/fauna/fauna_3.webp",
      "assets/images/fauna/fauna_4.webp",
      "assets/images/fauna/fauna_5.webp",
      "assets/images/fauna/fauna_6.webp",
      "assets/images/fauna/fauna_7.webp",
      "assets/images/fauna/fauna_8.webp",
      "assets/images/fauna/fauna_9.webp",
      "assets/images/fauna/fauna_10.webp",
    ],
  },
  astrofotografia: {
    title: "Astrofotografía",
    desc: "Fotografía del cielo y el universo",
    image: "assets/images/astro/astro_1.webp",
    carrusel : [
      "assets/images/astro/astro_1.webp",
      "assets/images/astro/astro_4.webp",
      "assets/images/astro/astro_6.webp",
    ],
    photos: [
      "assets/images/astro/astro_1.webp",
      "assets/images/astro/astro_2.webp",
      "assets/images/astro/astro_3.webp",
      "assets/images/astro/astro_4.webp",
      "assets/images/astro/astro_5.webp",
      "assets/images/astro/astro_6.webp",
      "assets/images/astro/astro_7.webp",
    ],
  },
  deporte: {
    title: "Deporte",
    desc: "Capturas de deportes y acción",
    image: "assets/images/deporte/deporte1.jpeg",
    carrusel : [],
    photos: [
      "assets/images/deporte/deporte1.jpeg",
      "assets/images/deporte/deporte2.jpeg",
    ],
  },
};